service: aws-binance-bot
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: python3.9

functions:
  binance_bot:
    handler: handler.binance_trade
    events:
      - http:
          path: /webhook
          method: POST
      - schedule:
          rate: rate(15 minutes)
          input:
            source: "polling"
            detail-type: "PollingRequest"

plugins:
  - serverless-python-requirements
