service: aws-binance-bot
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: python3.9

functions:
  trade_bot:
    handler: trade_bot.handler
    events:
      - eventBridge:
          pattern:
            source:
              - "discord_bot"
            detail-type:
              - "DiscordBotRequest"
      - schedule:
          rate: rate(15 minutes)
          input:
            source: "polling"
            detail-type: "PollingRequest"
  discord_bot:
    handler: discord_bot.handler
    events:
      - eventBridge:
          pattern:
            source:
              - "trade_bot"
            detail-type:
              - "TradeBotRequest"
      - http:
          path: /webhook
          method: POST

plugins:
  - serverless-python-requirements
