service: aws-binance-bot
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
        - events:EnableRule
        - events:DisableRule
      Resource: "*"
  environment:
    DISCORD_BOT_TOKEN: #TODO
    PUBLIC_KEY: #TODO
    DISCORD_CHANNEL_ID: #TODO
    SCHEDULE_RULE_NAME: #TODO!


functions:
  trade_bot:
    handler: trade_bot.handler
    events:
      - schedule:
          rate: rate(15 minutes)
          input:
            source: "polling"
            detail-type: "PollingRequest"
  discord_bot:
    handler: discord_bot.handler
    events:
      - eventBridge:
          pattern:
            source:
              - "trade_bot"
            detail-type:
              - "TradeBotRequest"
      - http:
          path: /webhook
          method: POST
          cors: true

plugins:
  - serverless-python-requirements
